apiVersion: v2
name: position-pal-chat-service
description: Helm chart for the Position PAL Chat Service

type: application
version: "1.15.0"
appVersion: "1.15.0"

dependencies:
  - name: cassandra
    version: "12.3.11"
    repository: "https://charts.bitnami.com/bitnami"