apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "chat-service.labels" . | nindent 4 }}
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaNumber }}
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      {{- include "cassandra.waitForDatabase" . | nindent 6 }}
      containers:
      {{- include "chat-service.container" . | nindent 8 }}
        