apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-chat-service-secrets
type: Opaque
data:
  rabbitmq-password: {{ .Values.rabbitmq.password | b64enc }}
  cassandra-password: {{ .Values.cassandra.dbUser.password | b64enc }}
  akka-license-key: {{ .Values.akkaLicenseKey | b64enc }}