apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chat-service.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.httpPort }}
      targetPort: {{ .Values.httpPort }}
      name: http
    - protocol: TCP
      port: {{ .Values.grpcPort }}
      targetPort: {{ .Values.grpcPort }}
      name: grpc
  type: ClusterIP
  selector:
  {{- include "chat-service.labels" . | nindent  4}}